runs:
  using: composite
  steps:
    - name: "Set up Python"
      uses: actions/setup-python@v6
      with:
        python-version-file: "pyproject.toml"

    - name: "Install uv"
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        cache-dependency-glob: uv.lock
