name: Python Code Quality
on: [push]
jobs:
  lockfile:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv lock --locked
  linting:
    runs-on: windows-latest
    needs: [lockfile]
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uvx ruff check .
  formatting:
    runs-on: windows-latest
    needs: [lockfile]
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uvx ruff format --check .
  typing:
    runs-on: windows-latest
    needs: [lockfile]
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv sync && uvx pyright --project .
  build:
    runs-on: windows-latest
    needs: [linting, formatting, typing]
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv build
