name: Python Code Quality
on:
  push:
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
env:
  UV_LOCKED: 1
jobs:
  lockfile:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Check lockfile
        run: uv lock --check
  linting:
    runs-on: windows-latest
    needs: [lockfile]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Run ruff check
        run: uvx ruff check .
  formatting:
    runs-on: windows-latest
    needs: [lockfile]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Run ruff format
        run: uvx ruff format --check .
  typing:
    runs-on: ubuntu-latest # currently does not sucessfully run on windows-latest
    needs: [lockfile]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Sync dependencies
        run: uv sync --all-extras --dev
      - name: Run pyright
        run: uvx pyright --project .
  build:
    runs-on: windows-latest
    needs: [linting, formatting, typing]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Run build
        run: uv build
